#include "casm/casm_io/Log.hh"
#include "casm/casm_io/json/InputParser_impl.hh"
#include "casm/clexmonte/canonical/io/InputData.hh"
#include "casm/clexmonte/canonical/io/json/InputData_json_io.hh"

using namespace CASM;

// ///////////////////////////////////////
// ccasm-clexmonte-canonical main:

void print_help() {
  int verbosity = Log::standard;
  bool show_clock = false;
  int indent_space = 4;
  Log log(std::cout, verbosity, show_clock, indent_space);
  log.set_width(80);

  log.paragraph("usage: ccasm-clexmonte-canonical [-h] [-V] inputfile");
  log << std::endl;

  log.paragraph(
      "ccasm-clexmonte-canonical is a program for running canonical Monte "
      "Carlo calculations using cluster expansions generated by CASM.");
  log << std::endl;

  log << "Options:" << std::endl << std::endl;

  // ## positional arguments
  log << "positional arguments:" << std::endl;
  log.increase_indent();

  // ### inputfile
  log.indent() << "inputfile" << std::endl;
  log.increase_indent();
  log.paragraph(
      "JSON formatted file containing parameters controlling the Monte Carlo "
      "calculation.");
  log.decrease_indent();
  log << std::endl;

  log.decrease_indent();
  log << std::endl;

  // ## optional arguments
  log << "optional arguments:" << std::endl;
  log.increase_indent();

  // ### -h
  log.indent() << "-h, --help" << std::endl;
  log.increase_indent();
  log.paragraph("Print help message and exit");
  log.decrease_indent();
  log << std::endl;

  // ### -h
  log.indent() << "-V, --version" << std::endl;
  log.increase_indent();
  log.paragraph("Print version number and exit");
  log.decrease_indent();
  log << std::endl;
}

int main(int argc, char *argv[]) {
  if (argc != 2) {
    print_help();
    return 1;
  }

  std::string param = argv[1];

  if (param == "-h" || param == "--help") {
    print_help();
    return 0;
  } else if (param == "-V" || param == "--version") {
    log() << "2.0.0-alpha" << std::endl;
    return 0;
  } else {
    fs::path inputfile = param;

    jsonParser json(inputfile);
    InputParser<clexmonte::canonical::InputData> parser(json);
    std::runtime_error error_if_invalid{
        "Error reading canonical Monte Carlo JSON input"};
    report_and_throw_if_invalid(parser, CASM::log(), error_if_invalid);

    clexmonte::canonical::run(*parser.value);

    return 0;
  }
}
