name: Testing build all on macos-latest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

env:
  SKBUILD_BUILD_OPTIONS: --verbose

jobs:
  build-depends:
    uses: ./.github/workflows/test-macos-dependencies.yml

  build:
    needs: build-depends
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up requirements & configuration variables
        run: |
          brew update
          brew install cmake
          pip install --upgrade pip wheel
          git submodule update --init --recursive
          pip install -r test_requirements.txt

      ### libcasm-global ###
      - name: restore libcasm-global cache
        id: cache-libcasm-global-restore
        uses: actions/cache/restore@v4
        with:
          path: CASMcode_global/dist
          key: ${{ runner.os }}-libcasm-global-v2-1-0

      ### libcasm-composition ###
      - name: restore libcasm-composition cache
        id: cache-libcasm-composition-restore
        uses: actions/cache/restore@v4
        with:
          path: CASMcode_composition/dist
          key: ${{ runner.os }}-libcasm-composition-v2-1-0

      ### libcasm-xtal ###
      - name: restore libcasm-xtal cache
        id: cache-libcasm-xtal-restore
        uses: actions/cache/restore@v4
        with:
          path: CASMcode_crystallography/dist
          key: ${{ runner.os }}-libcasm-xtal-v2-1-0

      ### libcasm-clexulator ###
      - name: restore libcasm-clexulator cache
        id: cache-libcasm-clexulator-restore
        uses: actions/cache/restore@v4
        with:
          path: CASMcode_clexulator/dist
          key: ${{ runner.os }}-libcasm-clexulator-v2-1-0

      ### libcasm-configuration ###
      - name: restore libcasm-configuration cache
        id: cache-libcasm-configuration-restore
        uses: actions/cache/restore@v4
        with:
          path: CASMcode_configuration/dist
          key: ${{ runner.os }}-libcasm-configuration-v2-1-0

      ### libcasm-monte ###
      - name: restore libcasm-monte cache
        id: cache-libcasm-monte-restore
        uses: actions/cache/restore@v4
        with:
          path: CASMcode_monte/dist
          key: ${{ runner.os }}-libcasm-monte-v2-1-0

      - name: Install CASM dependencies
        run: |
          pip install CASMcode_global/dist/*.whl
          pip install CASMcode_composition/dist/*.whl
          pip install CASMcode_crystallography/dist/*.whl
          pip install CASMcode_clexulator/dist/*.whl
          pip install CASMcode_configuration/dist/*.whl
          pip install CASMcode_monte/dist/*.whl
          pip install -r build_requirements.txt
          pip install -r test_requirements.txt
          echo "CASM_PREFIX=$(python -m libcasm.casmglobal --prefix)" >> "$GITHUB_ENV"

      - name: make
        shell: bash
        run: |
          pip install -v .

      - name: make test
        shell: bash
        run: |
          python -m pytest -rsap python/tests

      - name: Set up doc requirements
        run: |
          pip install -r doc_requirements.txt

